### ISSUE TITLE
unit tests?

### ISSUE THREAD

**Issue by DerManoMann** [peej/phpdoctor#64]
I spend some time today trying to make the unit tests work with a recent version of simpletest. Beside the fact that the code is badly broken in 5.3, a lot of tests actually seem to fail.

I will do some more testing with 5.2, time permitted.7

So, my question is: is there interest in that and should the tests pass or fail? Or am I missing something altogether?

Ta, mano

**Comment by DerManoMann** [comment]
Bump ... does anyone know or care at all? 

Thanks, mano

**Comment by tetsuo13** [comment]
I don't know why the unit tests haven't been maintained to ensure they pass but they definitely should. In theory the only place where it would be acceptable to have failing tests would be in a development branch.

Also, if we're sticking to SimpleTest (instead of the more standard PHPUnit) the tests should also be upgraded to work against the latest version. In my last brief look at them, they weren't compatible with the API changes in 1.1.

**Comment by DerManoMann** [comment]
Right, I'll create a version with working (even if failing) tests and we can take it from there.
I wonder - is support for PHP 4 still a hard requirement? I would vote for pushing that to at least 5.2, if not 5.3

**Comment by tetsuo13** [comment]
The maintainer has mentioned two years ago in #6 that PHP 4 compatibility is intended until the latest version of PHP makes it impossible to maintain PHP 4 backwards compatibility. I couldn't find anything more recent to see if this intention is still valid.

https://github.com/peej/phpdoctor/issues/6#issuecomment-242318

**Comment by DerManoMann** [comment]
covered by pull request #65
